### PR TITLE
A few fixes for folks getting started contributing to this plugin

### PR DESCRIPTION
**Pull request by EddyVerbruggen**
Enjoy.

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Lemme merge this with my evil commit access 😈

**Comment by NathanWalker** [comment]
You wanna bump and publish too? :)

**Comment by NathanWalker** [comment]
For the future - thanks for this btw 👍

**Comment by EddyVerbruggen** [comment]
Sure, can't hurt to be able to publish 😈

**Pull request merged**
