### PR TITLE
Radiobuttons

### PR DESCRIPTION
**Pull request by EddyVerbruggen**
This is not a native solution, I didn't have the need nor time for that, but with the current plugin you can turn the *behavior* of the checkboxes into radiobuttons. This doc shows how, and I've also added a working example to the ng-demo.

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Btw, I'm using this in an app as Tweeted [here](https://twitter.com/eddyverbruggen/status/872548477687001088).

**Comment by bradmartin** [comment]
@EddyVerbruggen wanna merge or you adding something?

**Comment by NathanWalker** [comment]
lgtm!

**Comment by EddyVerbruggen** [comment]
Thanks for checking, merging!

**Pull request merged**
