### PR TITLE
Allow styling with CSS

### PR DESCRIPTION
**Pull request by agisboye**
This allows setting `tint-color` and `fill-color` in CSS rather than XML.

### CODE REVIEW

**Comment by NathanWalker** [comment]
Thank you so much @agisboye ! Could you just resolve the merge conflict and update the demo to use both of these new CSS properties to test them out?

**Comment by triniwiz** [comment]
@NathanWalker this was added [tint-color](https://github.com/bradmartin/nativescript-checkbox/blob/master/checkbox.ios.ts#L31) [fill-color](https://github.com/bradmartin/nativescript-checkbox/blob/master/checkbox.ios.ts#L46) if it's working LMK

**Comment by agisboye** [comment]
I'd like to test it but #37 prevents from doing so. Any chance you can submit a new package?

**Comment by agisboye** [comment]
The CSS properties don't seem to work. Another user is having the same issue: #39.

**Comment by agisboye** [comment]
I'll close this PR, seeing as how you've ended up implementing the solution yourself. The issue about  it not working is being tracked in #39. I'll see if I can find the time to submit a fix.

**Pull request closed without merging**
