### PR TITLE
Support radio button appearance in Android

### LINKED ISSUE #59: Support radio button appearance in Android
Provide an option to enable the radio button appearance in Android. 

May be when `boxType` is set to `Circle` on Android, creating a RadioButton instance instead of a CheckBox instance will be a workaround?
```
export const enum BoxType {
  Circle = 0,
  Square = 1
}
...
this._android = new android.support.v7.widget[this.boxType == BoxType.Circle ? "AppCompatRadioButton" : "AppCompatCheckBox"](this._context, null);
```

### PR DESCRIPTION
**Pull request by manojdcoder**
Fixed #59

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Hey @bradmartin, can you please merge this? It's the last piece of the puzzle to make radiobuttons work perfectly 😄

**Comment by manojdcoder** [comment]
Thank you @EddyVerbruggen / @bradmartin. Also can you please make a release to NPM?

**Comment by EddyVerbruggen** [comment]
@manojdcoder I'm currently ironing out a few things before we can push to npm, but it will be shortly!

**Comment by bradmartin** [comment]
Thanks for handling it @EddyVerbruggen 👍

**Comment by EddyVerbruggen** [comment]
Sent and merged PR #63 to align iOS and Android implementations.

Bumped to 3.0.0 (and published to npm) because the default `boxType` (appearance) for iOS *had* to change to `square`. The reason is on Android `square` is a checkbox and `circle` is a radiobutton. On Android it's not only appearance, but the `circle` also acts like a radiobutton (you can't deselect it).

So for `boxType` to make sense and work consistently across platforms the default had to be the same, being `square`. That may be problematic to some (circular checkboxes are now square on iOS) so that meant I had to bump the major version. But still, folks can use `circle` on iOS and default or `square` on Android if they want the old appearance.

**Comment by manojdcoder** [comment]
@EddyVerbruggen After upgrading to `3.0.0` I'm getting the following error when building app with web pack, any idea why / how it could be solved?

```
ERROR in Unexpected value 'TNSCheckBoxModule in path_to_project/node_modules/nativescript-checkbox/angular/index.js' imported by the module 'QuestionModule in path_to_project/app/question/question.module.ts'. Please add a @NgModule annotation.

ERROR in ./main.aot.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in 'path_to_project/app'
 @ ./main.aot.ts 5:29-62
```

**Pull request merged**
